export interface Product {
  id: number;
  name: string;
  price: number;
  description: string;
  image: string;
  longDescription: string;
}

const products: Product[] = [
  {
    id: 100,
    name: 'Teknologi Informatika',
    price: 5.99,
    description: 'Pengantar Teknologi Informatika',
    image: 'http://localhost:8080/buku1.jpg',
    longDescription:
      'Hero Assassin di Mobile Legends saat ini sudah banyak dan cukup mengesankan dari segi kemampuannya hingga hal lainnya. Assassin di dalam match Mobile Legends sangat dibutuhkan keberadaannya. Tidak sedikit dari masing-masing tim yang memilih Hero Assassin ada di dalam timnya, baik sebagai carry ataupun penyumbang damage.',
  },
  {
    id: 2,
    name: 'React',
    price: 8.99,
    description: 'Belajar React dan Express',
    image: 'http://localhost:8080/buku2.jpg',
    longDescription:
      'Hero epickers yang memiliki kelebihan oleh hero Lesley adalah memiliki jangkauan skill yang sangat jauh, kelebihan ini membuat Lesley sangat mematikan karena mampu membunuh hero lawan dari kejauhan. Dari keempat skill yang dimiliki oleh hero ini, skill tiganya yaitu (Ultimate Snipe) adalah skill dengan jangkauan paling jauh. Seperti yang terlihat pada gambar di atas, Lesley meng-lock satu target dan menembakinya sebanyak empat kali.',
  },
  {
    id: 3,
    name: 'Node',
    price: 7.99,
    description: 'Menjadi Programmer Node Js',
    image: 'http://localhost:8080/buku3.jpg',
    longDescription:
      'The Dragon Spinner is a new take on an ancient toy. Made of durable polycarbonate, it is strong enough to withstand the force generated by its razor-sharp spinning capabilities. It also features our signature edition design to make it one-of-a-kind — and one that you and your friends will love. What better way to relieve stress and anxiety than with a simple fidget spinner?',
  },
  {
    id: 5,
    name: 'PHP',
    price: 7.99,
    description: 'Belajar PHP edisi lengkap',
    image: 'http://localhost:8080/buku4.jpg',
    longDescription:
      'Rainbow Flames are small (1.5″ in diameter or approx. 46mm) fidget spinner toys. They are fun for people of all ages, including adults and kids. Kids love to play with Rainbow Flames because they are easy to spin and they come in assorted colors, like blue, green, red, white, purple and yellow possible combinations. Rainbow Flames fidget spinners are great for killing time; perfect for daydreaming, calming nerves, focusing attention & relaxing; better than nail biting & knuckle cracking. Rainbow Flames fidget spinners can be successfully incorporated into therapy sessions as fidget toys',
  },
  {
    id: 6,
    name: 'Next',
    price: 6.99,
    description: 'Belajar Next JS',
    image: 'http://localhost:8080/buku5.jpg',
    longDescription:
      'Built with a 3v high-speed motor, this fidget spinner is sure to be a crowd pleaser. From the center axis to the buttons on each of the three caps, enough space was left between the pieces for a kinetic chain reaction -- creating a hypnotizing, spinning flowchart. The customizable caps give you 11 unique options to choose from. Our "Jammin" spinner comes in a stylish white box with a velvet lining and includes our standard 90 day manufacturer\'s warranty.',
  },
  {
    id: 7,
    name: 'React ',
    price: 8.99,
    description: 'Web Development with React',
    image: 'http://localhost:8080/buku6.jpg',
    longDescription:
      'This is the solid stainless steel fidget spinner that is perfect for any gold lover. It is build with 6 Fidget Spinner components giving it 6 super-sized bearings for maximum glide and endless spin time. A perfect combination of gold, steel & infinity.',
  },
  {
    id: 8,
    name: 'Hacking',
    price: 7.99,
    description: 'Ethical Hacking',
    image: 'http://localhost:8080/buku7.jpg',
    longDescription:
      "This unique fidget spinner has a jade highlight and is great for all ages. Great for anxiety, focusing, adhd, autism, quitting bad habits, staying awake and also helps with reducing stress and panic attacks. This product is designed in the USA and made from high quality materials. The weight and feel are perfect in the hands. It's not too light or to heavy allowing for long term use without causing fatigue in the hands. High Performance Gyroscopes With Smooth Rotation",
  },
  {
    id: 9,
    name: 'Python',
    price: 8.99,
    description: "Belajar Python untuk pemula",
    image: 'http://localhost:8080/buku8.jpg',
    longDescription:
      "Fidgeting is a human impulse. That's why we created the Rainbow Hearts: a fun and colorful fidget toy that brings together two of our most popular sleeves in one object. Rainbow Hearts is precision-machined in San Francisco, with a brushed stainless steel clicker, and clear acrylic rainbow colored hearts. And with all the customization that we offer, it will be truly unique!",
  },
  {
    id: 10,
    name: 'Data Science',
    price: 9.99,
    description: 'Beginning data science in R',
    image: 'http://localhost:8080/buku9.jpg',
    longDescription:
      "The Gold and Silver Gears Fidget Spinner, by Gear Beast, is a steal of a deal on a super flashy fidget spinner. The body spins on high-quality stainless steel bearings, while the center piece is made from brass. It comes in a variety of colors, so no matter your style you're sure to find a fidget spinner you'll fall in love with.",
  },
  {
    id: 11,
    name: 'Data science with R',
    price: 12.99,
    description:
      'Belajar Bahasa R untuk data science',
    image: 'http://localhost:8080/buku10.jpg',
    longDescription:
      "Did you know that a standard gear train has 3 gears? It is true! And, we've given you all three in this delightful fidget spinner. Spin away and watch your mind be blown away by the seemingly endless and rapid movement of these three little clockwork wheels.",
  },
];

export default products;
